export enum UsersActionTypes {
    STARTED_REQUEST_USERS = 'STARTED_REQUEST_USERS',
    REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS',
    REQUEST_USERS_FAILURE = 'REQUEST_USERS_FAILURE',
} 

export enum TodosActionTypes {
    STARTED_REQUEST_TODOS = 'STARTED_REQUEST_TODOS',
    REQUEST_TODOS_SUCCESS = 'REQUEST_TODOS_SUCCESS',
    REQUEST_TODOS_FAILURE = 'REQUEST_TODOS_FAILURE',
} 